name: Pull Request Validation
on: 
  pull_request:
    paths:
      - 'tf/**'
      - '!tf/dev/**'
      - '.github/**'

jobs:
  test:
    name: Validate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TERRAFORM_ENV_BASE64: ${{ secrets.TERRAFORM_ENV_BASE64 }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - run: |-
        _tfdir=tf/prod
        echo $TERRAFORM_ENV_BASE64 | base64 -d > tfvars
        source tfvars
        terraform -chdir=${_tfdir} init
        terraform -chdir=${_tfdir} validate